version: 2.1

orbs:
  torque: quali/torque@dev:alpha
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - torque/start-sandbox:
          sandbox-name: "test"
          blueprint: "[Sample]Bitnami Nginx Helm Chart"
          inputs: "{'replicaCount': '1'}"
      - run:
          name: Functional test
          command: |
            sleep 15
      - torque/end-sandbox:
          sandbox-id: SANDBOX_ID
workflows:
  leadeasy:
    jobs:
      - test
