name: CI
on:
  push:
    branches:
      - master

jobs:
  test-with-torque:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Start Torque Sandbox
      id: start-sandbox
      uses: QualiTorque/torque-start-environment@spaces
      with:
        space: dev
        blueprint_name: My nginx
        repository_name: qa-assets # new param
        inputs: Name=webapp, "Bla bla"=torque
        environment_name: abc
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        torque_hostname: preview.qtorque.io # only hostname, without schema
        timeout: 5 # set timeout in minutes if you want to wait until env is active

    - name: Testing
      id: test-app
      run: |
        echo "Running tests against sandbox with id: ${{ steps.start-sandbox.outputs.environment_id }}"
        echo "Sandbox details are: ${{ steps.start-sandbox.outputs.environment_details }}"
        sleep 30

    - name: Stop sandbox
      uses: QualiTorque/torque-end-environment@dev
      with:
        space: Sample
        environment_id: ${{ steps.start-sandbox.outputs.environment_id }}
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        torque_hostname: preview.qtorque.io
