name: CI
on:
  push:
    branches:
      - master

jobs:
  test-with-torque:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Start Torque Sandbox
      id: start-sandbox
      uses: QualiTorque/torque-start-sb-action@dockerize
      with:
        space: dev
        blueprint_name: nginx
        environment_name: abc
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        torque_hostname: preview.qtorque.io
        timeout: 30

    - name: Testing
      id: test-app
      run: |
        echo "Running tests against sandbox with id: ${{ steps.start-sandbox.outputs.environment_id }}"
        echo "Sandbox details are: ${{ steps.start-sandbox.outputs.environment_details }}"

    - name: Stop sandbox
      uses: QualiTorque/torque-end-sb-action@dockerize
      with:
        space: Sample
        environment_id: ${{ steps.start-sandbox.outputs.sandbox_id }}
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        torque_hostname: preview.qtorque.io
