name: CI
on:
  push:
    branches:
      - master

jobs:
  test-with-torque:
    runs-on: ubuntu-latest
    
    steps:
    - name: Start Torque Sandbox
      id: start-sandbox
      uses: QualiTorque/torque-start-sb-action@dockerize
      with:
        space: dev
        blueprint_name: jira
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        torque_url: https://preview.qtorque.io
        timeout: 30
        branch: main

#     - name: Testing
#       id: test-app
#       run: |
#         echo "Running tests against sandbox with id: ${{ steps.start-sandbox.outputs.sandbox_id }}"
#         echo "Sandbox details are: ${{ steps.start-sandbox.outputs.sandbox_details }}"

#     - name: Stop sandbox
#       uses: QualiTorque/torque-end-sb-action@dev
#       with:
#         space: Sample
#         sandbox_id: ${{ steps.start-sandbox.outputs.sandbox_id }}
#         torque_token: ${{ secrets.TORQUE_TOKEN }} 
