name: CI
on:
  push:
    branches:
      - master


jobs:
  test-with-torque:
    runs-on: ubuntu-latest
    
    steps:
    - name: Start Torque Sandbox
      id: start-sandbox
      uses: QualiTorque/torque-start-sb-action@dev
      with:
        space: Sample
        blueprint_name: "[Sample]Bitnami Nginx Helm Chart"
        inputs: "replicaCount=1"
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        timeout: 30
        duration: 10

    - name: Testing
      id: test-app
      run: |
        echo "Running tests against sandbox with id: ${{ steps.start-sandbox.outputs.sandbox_id }}"
        echo "Sandbox details are: ${{ steps.start-sandbox.outputs.sandbox_details }}"

    - name: Stop sandbox
      uses: QualiTorque/torque-end-sb-action@dev
      with:
        space: Sample
        sandbox_id: ${{ steps.start-sandbox.outputs.sandbox_id }}
        torque_token: ${{ secrets.TORQUE_TOKEN }} 
