name: CI
on:
  push:
    branches:
      - master

jobs:
  test-with-torque:
    runs-on: ubuntu-latest
    
    steps:
    - name: Start Torque Sandbox
      id: start-sandbox
      uses: QualiTorque/torque-start-sb-action@dev
      with:
        space: DBS
        blueprint_name: hello
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        timeout: 30

    - name: Testing
      id: test-app
      run: |
        echo "Running tests against sandbox with id: ${{ steps.start-sandbox.outputs.sandbox_id }}"
        echo "Sandbox details are: ${{ steps.start-sandbox.outputs.sandbox_details }}
